version: "3.5"
services:
  verification-oracle:
    image: localhost:5000/verification-oracle
    restart: always
    command:
      - ./verification-oracle
    ports:
      - 80:8080
    extra_hosts: []
    volumes:
      - type: bind
        source: /root/Projects/verification-oracle/config/default.json
        target: /app/config/default.json
      - type: bind
        source: /root/Projects/verification-oracle/config/local.json
        target: /app/config/local.json
    deploy:
      resources:
        limits:
          memory: 1000M
    environment:
      RUST_LOG: debug
    init: false
